2023/10/08 22:23:29 [error] 21#21: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://192.168.240.5:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/08 22:23:29 [error] 21#21: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://192.168.240.5:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/08 22:23:29 [error] 21#21: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://192.168.240.5:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/08 22:23:29 [error] 21#21: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.240.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://192.168.240.5:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/08 22:32:59 [error] 20#20: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.18.0.5:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/08 22:32:59 [error] 21#21: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.18.0.5:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/08 22:32:59 [error] 20#20: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.18.0.5:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/08 22:32:59 [error] 21#21: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.18.0.5:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 01:33:51 [error] 19#19: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.19.0.4:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 01:33:51 [error] 20#20: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.19.0.4:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 01:33:51 [error] 19#19: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.19.0.4:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 01:33:51 [error] 20#20: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.19.0.4:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 01:58:10 [error] 21#21: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.22.0.4:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 01:58:10 [error] 22#22: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.22.0.4:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 01:58:10 [error] 21#21: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.22.0.4:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 01:58:10 [error] 22#22: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.22.0.4:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 09:03:02 [error] 21#21: *32 upstream prematurely closed connection while reading response header from upstream, client: 172.25.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.25.0.4:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 09:03:02 [error] 20#20: *31 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.25.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.25.0.4:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 09:03:02 [error] 20#20: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.25.0.4:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/09 09:03:04 [error] 23#23: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://172.25.0.4:8080/databases", host: "api.clientsapp.local:8080"
2023/10/10 01:40:59 [error] 20#20: *381 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:40:59 [error] 21#21: *383 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:40:59 [error] 20#20: *381 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:40:59 [error] 21#21: *383 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:54:20 [error] 20#20: *411 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:54:20 [error] 20#20: *410 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:54:20 [error] 20#20: *411 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:54:20 [error] 20#20: *410 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:54:20 [error] 20#20: *411 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:58:01 [error] 21#21: *442 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:58:01 [error] 20#20: *443 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:58:01 [error] 21#21: *442 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:58:01 [error] 20#20: *443 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 01:58:01 [error] 21#21: *442 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:13:20 [error] 20#20: *475 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:13:20 [error] 21#21: *477 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:13:20 [error] 20#20: *475 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:13:20 [error] 21#21: *477 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:13:20 [error] 20#20: *475 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:17:01 [error] 21#21: *507 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:17:01 [error] 22#22: *506 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:17:01 [error] 22#22: *506 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:17:01 [error] 21#21: *507 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:17:01 [error] 22#22: *506 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:30:20 [error] 22#22: *538 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:30:20 [error] 22#22: *537 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:30:20 [error] 22#22: *538 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:30:20 [error] 22#22: *537 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:34:02 [error] 21#21: *567 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:34:02 [error] 21#21: *568 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:34:02 [error] 21#21: *567 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:34:02 [error] 21#21: *568 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:42:20 [error] 21#21: *597 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:42:20 [error] 21#21: *599 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:42:20 [error] 21#21: *597 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.27.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 02:42:20 [error] 21#21: *599 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.27.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:14:53 [error] 22#22: *336 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.28.0.5:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:14:53 [error] 23#23: *338 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.28.0.5:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:14:53 [error] 22#22: *336 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.28.0.5:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:14:53 [error] 23#23: *338 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.28.0.5:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:14:54 [error] 22#22: *342 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://172.28.0.5:8080/databases", host: "api.clientsapp.local:8080"
2023/10/10 04:16:07 [error] 22#22: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.29.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:16:07 [error] 20#20: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.29.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:16:07 [error] 22#22: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.29.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:16:07 [error] 20#20: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.29.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:16:42 [error] 24#24: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.29.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:16:42 [error] 24#24: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.29.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:16:42 [error] 24#24: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.29.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:16:42 [error] 24#24: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.29.0.2:8080/collections/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:16:42 [error] 24#24: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.29.0.2:8080/databases/", host: "0.0.0.0:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:22:10 [error] 21#21: *94 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.29.0.2:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:22:10 [error] 23#23: *93 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://172.29.0.2:8080/databases", host: "api.clientsapp.local:8080"
2023/10/10 04:22:10 [error] 21#21: *94 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.29.0.2:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:22:10 [error] 23#23: *97 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.29.0.2:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:22:10 [error] 23#23: *97 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.29.0.2:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:22:56 [error] 22#22: *103 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://172.29.0.2:8080/databases", host: "api.clientsapp.local:8080"
2023/10/10 04:22:57 [error] 22#22: *105 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://172.29.0.2:8080/databases", host: "api.clientsapp.local:8080"
2023/10/10 04:23:00 [error] 20#20: *129 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.29.0.2:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:23:00 [error] 20#20: *130 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.29.0.2:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:23:00 [error] 20#20: *129 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.29.0.2:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:23:00 [error] 20#20: *130 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.29.0.2:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:23:00 [error] 20#20: *129 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.29.0.2:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:23:20 [error] 22#22: *138 connect() failed (111: Connection refused) while connecting to upstream, client: 172.29.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://172.29.0.2:8080/databases", host: "api.clientsapp.local:8080"
2023/10/10 04:24:33 [error] 24#24: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.30.0.5:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:24:33 [error] 22#22: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://172.30.0.5:8080/databases", host: "api.clientsapp.local:8080"
2023/10/10 04:24:33 [error] 22#22: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.30.0.5:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:24:33 [error] 24#24: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.30.0.5:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 04:24:33 [error] 22#22: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.30.0.5:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:36:15 [error] 25#25: *735 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.30.0.5:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:36:15 [error] 23#23: *736 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://172.30.0.5:8080/databases", host: "api.clientsapp.local:8080"
2023/10/10 08:36:15 [error] 25#25: *737 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.30.0.5:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:36:15 [error] 25#25: *735 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.30.0.5:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:36:15 [error] 25#25: *737 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.30.0.5:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:37:00 [error] 25#25: *767 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.30.0.5:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:37:00 [error] 25#25: *766 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.30.0.5:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:37:00 [error] 25#25: *767 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.30.0.5:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:37:00 [error] 25#25: *766 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://172.30.0.5:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:37:00 [error] 25#25: *767 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://172.30.0.5:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:37:05 [error] 25#25: *774 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://172.30.0.5:8080/databases", host: "api.clientsapp.local:8080"
2023/10/10 08:50:58 [error] 22#22: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://192.168.0.4:8080/databases", host: "api.clientsapp.local:8080"
2023/10/10 08:50:58 [error] 19#19: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://192.168.0.4:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:50:58 [error] 20#20: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://192.168.0.4:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:50:58 [error] 20#20: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: api.clientsapp.local, request: "GET /collections/ HTTP/1.1", upstream: "http://192.168.0.4:8080/collections/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:50:58 [error] 19#19: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: api.clientsapp.local, request: "GET /databases/ HTTP/1.1", upstream: "http://192.168.0.4:8080/databases/", host: "api.clientsapp.local:8080", referrer: "http://clientsapp.local:5173/"
2023/10/10 08:53:39 [error] 21#21: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://192.168.0.4:8080/databases", host: "api.clientsapp.local:8080"
2023/10/10 08:55:05 [error] 24#24: *39 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: api.clientsapp.local, request: "GET /databases HTTP/1.1", upstream: "http://192.168.0.4:8080/databases", host: "api.clientsapp.local:8080"
